package: env-middleware
version: "1.0.0"
author: Emanuel Mistretta
supportpage: https://github.com/oldjazjef/redaxo-addon-env-middleware

requires:
  redaxo: "^5.10.0"
  php: ">=7.3"

boot: true

permissions:
  - env-middleware[]
  - env-middleware[settings]
  - env-middleware[environments]
  - env-middleware[oauth]
  - env-middleware[proxy]

page:
  title: "translate:env_middleware_title"
  perm: admin
  subpages:
    settings: 
      title: "translate:env_middleware_settings" 
      perm: env-middleware[settings]
    environments: 
      title: "translate:env_middleware_environments"
      perm: env-middleware[environments]
    oauth: 
      title: "translate:env_middleware_oauth" 
      perm: env-middleware[oauth]
    proxy: 
      title: "translate:env_middleware_proxy" 
      perm: env-middleware[proxy]
